{
 "title": "Monitoring recom service",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Количество запросов разных типов рекомендаций в минуту",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "increase(request_personal_count_total[1m])",
     "legendFormat": "personal recommendation"
    },
    {
     "expr": "increase(request_default_count_total[1m])",
     "legendFormat": "default recommendation"
    }
   ]
  },
  {
   "title": "Потребление RAM",
   "type": "gauge",
   "description": "Потребление RAM в моменте",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "process_virtual_memory_bytes", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Трафик (traffic)",
   "type": "timeseries",
   "description": "Количество HTTP-запросов в секунду",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rate(http_request_duration_seconds_count{handler=\"/recommendations\"}[1m])",
     "legendFormat": "{{handler}}"
    }
   ]
  },
  {
   "title": "Задержка (latency)",
   "type": "timeseries",
   "description": "Среднее время обработки пользовательских запросов, пришедших за крайнюю минуту.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "sec" } },
   "targets": [
    {
     "expr": "increase(http_request_duration_seconds_sum{handler=\"/recommendations\", method=\"POST\"}[1m]) / increase(http_request_duration_seconds_count{handler=\"/recommendations\", method=\"POST\"}[1m])",
     "legendFormat": "{{handler}}"
    }
   ]
  }
 ]
}