# run_mlflow_server.sh
# запуск командой source ./mlflow_server/run_mlflow_server.sh

export MLFLOW_S3_ENDPOINT_URL=https://storage.yandexcloud.net
export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
export AWS_BUCKET_NAME=$S3_BUCKET_NAME

# Логирование переменных окружения
# echo "DB_DESTINATION_USER: $DB_DESTINATION_USER"
# echo "DB_DESTINATION_PASSWORD: $DB_DESTINATION_PASSWORD"
# echo "DB_DESTINATION_HOST: $DB_DESTINATION_HOST"
# echo "DB_DESTINATION_PORT: $DB_DESTINATION_PORT"
# echo "DB_DESTINATION_NAME: $DB_DESTINATION_NAME"
# echo "AWS_BUCKET_NAME: $AWS_BUCKET_NAME"

mlflow server \
  --backend-store-uri postgresql://$DB_DESTINATION_USER:$DB_DESTINATION_PASSWORD@$DB_DESTINATION_HOST:$DB_DESTINATION_PORT/$DB_DESTINATION_NAME\
  --registry-store-uri postgresql://$DB_DESTINATION_USER:$DB_DESTINATION_PASSWORD@$DB_DESTINATION_HOST:$DB_DESTINATION_PORT/$DB_DESTINATION_NAME\
  --default-artifact-root s3://$AWS_BUCKET_NAME \
  --no-serve-artifacts